#%RAML 1.0
title: calsi
version: v2
protocols: [http,https]
description: this is demo api from scratch

/add:
  get:
    queryParameters:
      number1: 
       type: integer
       required: true
       example: 23
      number2:
        type: integer
        required: true
        example: 12
    responses:
      200:
        body:
          application/json:
            example:
              {
                "msg" : "add is 60"
              }
/division:
  put:
    queryParameters:
      number1:
       type: integer
       required: true
       example: 23
      number2:
        type: integer
        required: true
        example: 40
    responses: 
     201:
      body:
        application/json:
          example:
            {
              "msg" : "division is 56"
            }
/Multiplication:
  patch:
    queryParameters:
      number1:
       type: integer
       required: true
       example: 23
      number2:
        type: integer
        required: true
        example: 40
    responses: 
     201:
      body:
        application/json:
          example:
            {
              "msg" : "Multiplication is 500"
            }
/subtraction:
  post:
    queryParameters:
      number1:
        type: integer
        required: true
      number2:
        type: integer
        required: true
    responses:
      201:
        body:
          application/json:
            example:
              {
                "Msg": "Subtraction is 68"
              }
      
          
         
      

      
  